package entidades;
// Generated 14/07/2019 06:58:19 PM by Hibernate Tools 4.3.1



/**
 * Juguete generated by hbm2java
 */
public class Juguete  implements java.io.Serializable {


     private int idJuguete;
     private String marca;
     private int precio;

    public Juguete() {
    }

    public Juguete(int idJuguete, String marca, int precio) {
       this.idJuguete = idJuguete;
       this.marca = marca;
       this.precio = precio;
    }
   
    public int getIdJuguete() {
        return this.idJuguete;
    }
    
    public void setIdJuguete(int idJuguete) {
        this.idJuguete = idJuguete;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }




}


